[package]
name = "test_talib"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
engine = { path = "../../engine" }
paste = "1.0.15"
types = { path = "../../types" }
ordered-float.workspace = true
serde_json.workspace = true
