


[package]
name = "database"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sqlx = {version = "0.8.3", features = ["runtime-tokio", "sqlite"]}
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
sea-orm = { version = "1.1.7", features = [ "sqlx-sqlite","runtime-tokio", "macros", "chrono","with-chrono" ] }
chrono.workspace = true
migration = { path = "../migration" }
sea-orm-migration = {version="1.1.7", features = ["sqlx-sqlite","runtime-tokio"]}
