[package]
name = "entity"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sea-orm.workspace = true
serde.workspace = true
star-river-core = { path = "../star-river-core" }
chrono-tz.workspace = true