[package]
name = "event-center"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
types = {path = "../types"}
utils = {path = "../utils"}
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
strum.workspace = true
strum_macros.workspace = true
tracing.workspace = true
reqwest.workspace = true

