[project]
name = "script"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "metatrader5>=5.0.5120",
    "pyinstaller>=6.14.2",
    "pytz>=2025.2",
    "uvicorn[standard]>=0.35.0",
]
