[package]
name = "test_cancel_handle"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
tokio-util = {version = "0.7.14"}