[package]
name = "indicator-engine"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
build = "build.rs"

[dependencies]
event-center = {path = "../event-center"}
types = {path = "../types"}
utils = {path = "../utils"}
data-cache = {path = "../data-cache"}
uuid.workspace = true
tokio.workspace = true
tracing.workspace = true
serde_json.workspace = true
strum.workspace = true



[build-dependencies]
cc = "1.2"
bindgen = "0.71.1"
