[package]
name = "ta-lib"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

chrono.workspace = true
snafu.workspace = true
paste.workspace = true
serde.workspace = true
serde_json.workspace = true
deepsize.workspace = true
strum.workspace = true
ordered-float.workspace = true
axum.workspace = true

[lints]
workspace = true

[build-dependencies]
cc = "1.2"
bindgen = "0.72.1"
