[package]
name = "zero_mq"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
zeromq = {version = "0.4.1", features = ["tokio"]}
serde.workspace = true
strum.workspace = true